
image: python:3.6

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - apt update -y
  - apt install -y kicad
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install kicost
  - pip install --no-compile kibot

bom:
  script:
    - pwd
    - ls -la /
    - ls -la *
    - kicost -i ./ecad/MainBoard/MainBoard.xml -o kicost.xlsx
  artifacts:
    paths:
      - ./*.xlsx

3d_exports:
  script:
    - pwd
    - kibot render_3d ./ecad/MainBoard/MainBoard.kicad_pcb
